[[redirects]]
 from = "/latest"
 to = "https://github.com/ojkelly/yarn.build/releases/download/v0.9.32/plugin-build.js"
 status = 200
 force = true


[[redirects]]
 from = "/release/*"
 to = "https://github.com/ojkelly/yarn.build/releases/download/:splat/plugin-build.js"
 status = 200
 force = true
