on: [pull_request]

name: Build and Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check dependencies
        run: |
          yarn install --check-cache

      - name: Prettier
        # run yarn style:fix if your PR fails here
        run: |
          yarn style:check

      - name: Build plugins
        run: |
          yarn build -c update-local
      - name: Build Example
        run: |
          yarn build --ignore-cache packages/examples/lorem-ipsum
      - name: Test
        run: |
          yarn test --ignore-cache
      - uses: actions/upload-artifact@v2
        with:
          name: plugins-all
          path: .yarn/plugins/@ojkelly

  integration-test:
    name: Integration Test
    needs: [build]
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          name: plugins-all
          path: .yarn/plugins/@ojkelly
      - name: Install packages
        run: yarn install --immutable --immutable-cache
      - name: Build plugin
        run: yarn integration:build
      - name: Run integration tests
        run: cd e2e/lambda-project && yarn install --immutable --immutable-cache && yarn run integration
